"""Initial tables

Revision ID: c96b0282b747
Revises: 
Create Date: 2026-01-17 00:06:09.981073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96b0282b747'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('retire_age', sa.Integer(), nullable=True),
    sa.Column('life_expectancy', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('assumptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('inflation', sa.Float(), nullable=True),
    sa.Column('pre_retire_roi', sa.Float(), nullable=True),
    sa.Column('post_retire_roi', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumptions_id'), 'assumptions', ['id'], unique=False)
    op.create_table('cash_flows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('primary_income', sa.Float(), nullable=True),
    sa.Column('rental_income', sa.Float(), nullable=True),
    sa.Column('other_income', sa.Float(), nullable=True),
    sa.Column('essential_expenses', sa.Float(), nullable=True),
    sa.Column('lifestyle_expenses', sa.Float(), nullable=True),
    sa.Column('linked_emis', sa.Float(), nullable=True),
    sa.Column('linked_investments', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flows_id'), 'cash_flows', ['id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('current_cost', sa.Float(), nullable=True),
    sa.Column('target_type', sa.Enum('AGE', 'DATE', name='targettype'), nullable=True),
    sa.Column('target_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('investment_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('MF', 'STOCK', 'FD', name='investmenttype'), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('monthly_sip', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_assets_id'), 'investment_assets', ['id'], unique=False)
    op.create_table('liabilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('HOME', 'CAR', 'PERSONAL', name='liabilitytype'), nullable=True),
    sa.Column('outstanding', sa.Float(), nullable=True),
    sa.Column('emi', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liabilities_id'), 'liabilities', ['id'], unique=False)
    op.create_table('real_estate_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('loan_outstanding', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_estate_assets_id'), 'real_estate_assets', ['id'], unique=False)
    op.create_table('spouses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('working_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spouses_id'), 'spouses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spouses_id'), table_name='spouses')
    op.drop_table('spouses')
    op.drop_index(op.f('ix_real_estate_assets_id'), table_name='real_estate_assets')
    op.drop_table('real_estate_assets')
    op.drop_index(op.f('ix_liabilities_id'), table_name='liabilities')
    op.drop_table('liabilities')
    op.drop_index(op.f('ix_investment_assets_id'), table_name='investment_assets')
    op.drop_table('investment_assets')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_cash_flows_id'), table_name='cash_flows')
    op.drop_table('cash_flows')
    op.drop_index(op.f('ix_assumptions_id'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
